export type ModelAccess = "free" | "pro" | "premium";

export type DetoxModel = {
  id: string;
  displayName: string;
  emoji: string;
  access: ModelAccess;
  category: string;
  description: string;
  backendModel: string;
  maxTokens: number;
  enabled: boolean;
};

export const DETOX_MODELS: DetoxModel[] = [
  {
    id: "flash-1.0",
    displayName: "Flash 1.0",
    emoji: "⚡",
    access: "free",
    category: "Instant Answers",
    description: "Fast, clean answers for quick questions, small doubts, and daily chat.",
    backendModel: "mistral-small-latest",
    maxTokens: 800,
    enabled: true,
  },
  {
    id: "scholar-1.4",
    displayName: "Scholar 1.4",
    emoji: "📚",
    access: "free",
    category: "Study Help",
    description: "Friendly tutor mode for notes, homework, chapter explanations, summaries, and exam prep.",
    backendModel: "mistral-medium-latest",
    maxTokens: 1400,
    enabled: true,
  },
  {
    id: "spark-1.8",
    displayName: "Spark 1.8",
    emoji: "💡",
    access: "free",
    category: "Ideas",
    description: "Creative idea engine for apps, websites, games, YouTube, business names, and projects.",
    backendModel: "mistral-medium-latest",
    maxTokens: 1400,
    enabled: true,
  },
  {
    id: "echo-1.6",
    displayName: "Echo 1.6",
    emoji: "📝",
    access: "free",
    category: "Writing",
    description: "Clean, polished writing and rewriting for messages, captions, emails, bios, and grammar.",
    backendModel: "mistral-small-latest",
    maxTokens: 1200,
    enabled: true,
  },
  {
    id: "cosmo-1.2",
    displayName: "Cosmo 1.2",
    emoji: "🧠",
    access: "free",
    category: "Deep Thinking",
    description: "For deep thinking, planning, ideas, and smart conversations.",
    backendModel: "mistral-medium-latest",
    maxTokens: 1500,
    enabled: true,
  },
  {
    id: "gamma-2.0",
    displayName: "Gamma 2.0",
    emoji: "🧩",
    access: "free",
    category: "Problem Solving",
    description: "For logic, reasoning, math, and step-by-step answers.",
    backendModel: "mistral-medium-latest",
    maxTokens: 1500,
    enabled: true,
  },
  {
    id: "nova-1.5",
    displayName: "Nova 1.5",
    emoji: "⚡",
    access: "free",
    category: "Fast Chat",
    description: "For quick and simple AI replies.",
    backendModel: "mistral-small-latest",
    maxTokens: 900,
    enabled: true,
  },
  {
    id: "orion-2.9",
    displayName: "Orion 2.9",
    emoji: "💻",
    access: "pro",
    category: "High-Level Coding",
    description: "For coding, debugging, apps, websites, and full-stack projects.",
    backendModel: "mistral-large-latest",
    maxTokens: 3000,
    enabled: true,
  },
  {
    id: "mentor-3.0",
    displayName: "Mentor 3.0",
    emoji: "🎓",
    access: "pro",
    category: "Study",
    description: "For study notes, summaries, quizzes, and exam preparation.",
    backendModel: "mistral-medium-latest",
    maxTokens: 2500,
    enabled: true,
  },
  {
    id: "lyra-3.2",
    displayName: "Lyra 3.2",
    emoji: "✍️",
    access: "pro",
    category: "Writing",
    description: "For writing, captions, emails, scripts, and content.",
    backendModel: "mistral-medium-latest",
    maxTokens: 2500,
    enabled: true,
  },
  {
    id: "penton-4.4",
    displayName: "Penton 4.4",
    emoji: "👑",
    access: "premium",
    category: "Premium Multitasking",
    description: "The most powerful Detox AI model for advanced multitasking.",
    backendModel: "mistral-large-latest",
    maxTokens: 5000,
    enabled: true,
  },
  {
    id: "titan-5.0",
    displayName: "Titan 5.0",
    emoji: "🚀",
    access: "premium",
    category: "Project Builder",
    description: "For full apps, websites, startup blueprints, and big systems.",
    backendModel: "mistral-large-latest",
    maxTokens: 5000,
    enabled: true,
  },
  {
    id: "sentinel-2.7",
    displayName: "Sentinel 2.7",
    emoji: "🛡️",
    access: "premium",
    category: "Security",
    description: "For privacy, safety, bug checking, and moderation.",
    backendModel: "mistral-medium-latest",
    maxTokens: 3000,
    enabled: true,
  },
  {
    id: "prism-3.8",
    displayName: "Prism 3.8",
    emoji: "🎨",
    access: "premium",
    category: "Creative Design",
    description: "For UI/UX, design ideas, branding, and creative systems.",
    backendModel: "mistral-medium-latest",
    maxTokens: 3000,
    enabled: true,
  },
  {
    id: "atlas-4.0",
    displayName: "Atlas 4.0",
    emoji: "📊",
    access: "premium",
    category: "Business",
    description: "For analytics, product strategy, and business planning.",
    backendModel: "mistral-large-latest",
    maxTokens: 4000,
    enabled: true,
  },
];

export function getDetoxModel(modelId: string) {
  return DETOX_MODELS.find((model) => model.id === modelId && model.enabled);
}
